kind: Service
apiVersion: v1
metadata:
  name: deployjava
spec:
  type: NodePort
  selector:
    app: deployjava
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployjava
  labels:
    app: deployjava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployjava
  template:
    metadata:
      labels:
        app: deployjava
    spec:
      containers:
      - name: deployjava
        image: $DOCKER_IMAGE_NAME
        ports:
        - containerPort: 8080
