kind: Service
apiVersion: v1
metadata:
  name: space-game
spec:
  type: NodePort
  selector:
    app: space-game
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: space-game
  labels:
    app: space-game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: space-game
  template:
    metadata:
      labels:
        app: space-game
    spec:
      containers:
      - name: spacegame
        image: $DOCKER_IMAGE_NAME
        ports:
        - containerPort: 8080
